services:
  knox-frontend-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
      target: builder
    container_name: knox-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - node_modules_volume:/app/node_modules
    command: pnpm dev --host

volumes:
  node_modules_volume: